import Head from "next/head";

import styles from "../styles/Home.module.css";
import {
  HStack,
  Flex,
  Text,
  Image,
  Button,
  VStack,
  Box,
  SimpleGrid,
  AspectRatio,
  Divider,
  IconButton,
} from "@chakra-ui/react";
import { Team } from "../Component/team";
import { BsFacebook, BsInstagram } from "react-icons/bs";
import Link from "next/link";
const blue = "#3b21a1";
const green = "#48ddcb";

export default function Home() {
  const data = [
    { title: "Community" },
    { title: "Technology" },
    { title: "Influence" },
    { title: "System" },
    { title: "Process" },
  ];
  const text = "24px";
  const icon = [BsFacebook, BsInstagram];

  return (
    <>
      <Head>
        <title>Bit academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex flexDir={"column"} bg={blue}>
          <Box h="100px" />
          <HStack
            w="100%"
            // bg="RGBA(0, 0, 0, 0.3)"
            bg={blue}
            zIndex="100"
            color={"black"}
            transition="ease .2s"
            boxShadow={"xl"}
            py="15px"
            pos="fixed"
            justifyContent={"center"}
          >
            <HStack w="70%" justifyContent={"space-between"}>
              <Image
                opacity={"1"}
                w={"200px"}
                src={
                  "https://cdn.discordapp.com/attachments/1000991557886947358/1061272837555507200/Asset_6.png"
                }
              />
              <Button>Өргөдөл илгээх</Button>
            </HStack>
          </HStack>

          <HStack
            justifyContent={"space-between"}
            color={"white"}
            w="70%"
            mx="auto"
          >
            <Flex flexDir={"column"} justifyContent={"start"} w="40%">
              <Text fontSize={"85px"}>MORE THAN CODING</Text>
              <Text fontSize={text} textAlign={"start"}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
                tempore quas iure libero facere beatae temporibus suscipit
                quisquam possimus dolorum quis ullam animi quo iste repellat
                nesciunt doloremque fugiat! Culpa!
              </Text>

              <Button w="30%" borderRadius={"none"} bg={green} color={"black"}>
                Click me
              </Button>
            </Flex>

            <Image
              w="508px"
              src="https://cdn.discordapp.com/attachments/1000991557886947358/1061276422833967164/7_copy_1_1.png"
            />
          </HStack>
          <Box h="100px" />
          <VStack color={"white"} w="50%" mx="auto">
            <Image
              w="357px"
              h="110"
              src="https://cdn.discordapp.com/attachments/1000991557886947358/1061278101872578580/pe8_2.png"
            />
            <Text w="80%" fontSize={"24px"} textAlign={"center"}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              tempore quas iure libero facere beatae temporibus suscipit
              quisquam possimus dolorum quis ullam animi quo iste repellat
              nesciunt doloremque fugiat! Culpa!
            </Text>
          </VStack>
          <VStack>
            <VStack>
              <Text fontSize={"6xl"} color="white">
                What we teach?
              </Text>
            </VStack>
            <SimpleGrid
              spacing={3}
              columns={[1, 1, 2, 2, 3]}
              w="50%"
              justifyContent={"center"}
              alignContent="center"
            >
              {data.map((el: any, ind: number) => {
                return (
                  <AspectRatio>
                    <VStack>
                      <Flex
                        m="20px"
                        className="container"
                        w="100%"
                        height="100%"
                      >
                        <div className="card">
                          <Flex
                            mx="auto"
                            p={["20px", "40px", "40px", "70px"]}
                            w="100%"
                            h="100%"
                            className="front"
                            borderRadius={"12px"}
                            bg={green}
                          >
                            <Text fontSize={"4xl"} color={blue}>
                              {el.title}
                            </Text>
                          </Flex>
                          <div className="back">
                            <h1>Back of Card</h1> <div>description</div>
                          </div>
                        </div>
                      </Flex>
                    </VStack>
                  </AspectRatio>
                );
              })}
            </SimpleGrid>
          </VStack>
          <VStack w="100%" justifyContent={"center"} mx="auto">
            <Team />
          </VStack>
          <VStack>
            <Button p="10px" m="20px">
              Өргөдөл илгээх
            </Button>
          </VStack>
          <Divider />
          <HStack my="20px" justifyContent="space-between" px="80px">
            <Image
              w={"200px"}
              src="https://cdn.discordapp.com/attachments/1000991557886947358/1061272837555507200/Asset_6.png"
            />
            <Text color={"white"}>© 2023 Bit Academy</Text>
            <HStack>
              <Link
                href="https://www.facebook.com/bit.academy.official"
                target="_blank"
              >
                <IconButton
                  bg="none"
                  color={green}
                  aria-label="facebook"
                  icon={<BsFacebook size={"30px"} />}
                />
              </Link>
              <Link
                href="https://www.facebook.com/bit.academy.official"
                target="_blank"
              >
                <IconButton
                  bg="none"
                  color={green}
                  aria-label="facebook"
                  icon={<BsInstagram size={"30px"} />}
                />
              </Link>
              {/* {icon.map((el: any, ind: number) => {
                return (
                  <el/>
                )
              })} */}
            </HStack>
          </HStack>
        </Flex>
      </main>
    </>
  );
}
