import Head from "next/head";

import styles from "../styles/Home.module.css";
import {
  HStack,
  Flex,
  Text,
  Image,
  Button,
  VStack,
  Box,
  SimpleGrid,
  AspectRatio,
  Divider,
  IconButton,
} from "@chakra-ui/react";
import { Team } from "../Component/team";
import { BsFacebook, BsInstagram } from "react-icons/bs";

import {
  Link as Links,
  Button as Buttons,
  Element,
  Events,
  animateScroll as scroll,
  scrollSpy,
  scroller,
} from "react-scroll";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
const blue = "#3b21a1";
const green = "#48ddcb";

export default function Home() {
  const data = [
    { title: "Community" },
    { title: "Technology" },
    { title: "Influence" },
    { title: "System" },
    { title: "Process" },
  ];
  const text = "24px";
  const icon = [BsFacebook, BsInstagram];
  const [scrollPos, setScrollPos] = useState(0);
  const wrapperRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const handleScroll = () => {
      setScrollPos(wrapperRef.current!.scrollTop);
    };
    if (wrapperRef.current) {
      wrapperRef.current.addEventListener("scroll", handleScroll);
    }
    return () => {
      wrapperRef.current!.removeEventListener("scroll", handleScroll);
    };
  }, [scrollPos]);

  return (
    <>
      <Head>
        <title>Bit academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex flexDir={"column"} bg={blue}>
          <Box h="100px" />
          <HStack
            id="#home"
            w="100%"
            // bg="RGBA(0, 0, 0, 0.3)"
            bg={blue}
            zIndex="100"
            color={"black"}
            transition="ease .2s"
            boxShadow={"xl"}
            py="15px"
            pos="fixed"
            justifyContent={"center"}
          >
            <HStack w="70%" justifyContent={"space-between"}>
              <Link href={"#home"}>
                <Image
                  opacity={"1"}
                  w={"200px"}
                  src={
                    "https://cdn.discordapp.com/attachments/1000991557886947358/1061272837555507200/Asset_6.png"
                  }
                />
              </Link>
              <Button>Өргөдөл илгээх</Button>
            </HStack>
          </HStack>

          <VStack
            id="#more"
            // justifyContent={"space-evenly"}
            color={"white"}
            w="70%"
            mx="auto"
          >
            <Image
              w="808px"
              src="https://cdn.discordapp.com/attachments/1001000360296587344/1061854189770252339/7_copy_1_2.png"
            />

            <Flex flexDir={"column"} justifyContent={"start"} w="40%">
              <Text fontSize={"85px"}>MORE THAN CODING</Text>
              <Box h="20px" />
              <Text fontSize={text} textAlign={"start"}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
                tempore quas iure libero facere beatae temporibus suscipit
                quisquam possimus dolorum quis ullam animi quo iste repellat
                nesciunt doloremque fugiat! Culpa!
              </Text>
              <Box h="50px" />
              <Button w="30%" borderRadius={"none"} bg={green} color={"black"}>
                Click me
              </Button>
            </Flex>
          </VStack>
          <Box h="200px" />
          <VStack ref={wrapperRef} color={"white"} w="50%" mx="auto">
            <Image src="https://cdn.discordapp.com/attachments/1000991557886947358/1061278101872578580/pe8_2.png" />
            <Box h="50px" />
            <Text w="80%" fontSize={"24px"} textAlign={"center"}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              tempore quas iure libero facere beatae temporibus suscipit
              quisquam possimus dolorum quis ullam animi quo iste repellat
              nesciunt doloremque fugiat! Culpa!
            </Text>
          </VStack>
          <Box h="150px" />
          <VStack id="#what" w="100%" justifyContent={"center"}>
            <VStack>
              <Text fontSize={"85px"} color="white">
                What we teach?
              </Text>
            </VStack>

            <SimpleGrid
              spacing={3}
              columns={[1, 1, 2, 2, 3]}
              w="50%"
              justifyContent={"center"}
              alignContent="center"
              pb="150px"
            >
              {data.map((el: any, ind: number) => {
                return (
                  <AspectRatio>
                    <VStack>
                      <Flex
                        m="20px"
                        className="container"
                        w="100%"
                        height="100%"
                      >
                        <div className="card">
                          <Flex
                            mx="auto"
                            p={["20px", "40px", "40px", "70px"]}
                            w="100%"
                            h="100%"
                            className="front"
                            borderRadius={"12px"}
                            bg={green}
                          >
                            <Text fontSize={"4xl"} color={blue}>
                              {el.title}
                            </Text>
                          </Flex>
                          <div className="back">
                            <h1>Back of Card</h1> <div>description</div>
                          </div>
                        </div>
                      </Flex>
                    </VStack>
                  </AspectRatio>
                );
              })}
            </SimpleGrid>
          </VStack>

          <VStack id="#team" justifyContent={"center"} mx="auto">
            <Team />
          </VStack>
          <VStack pb="100px">
            <Button p="10px" m="20px">
              Өргөдөл илгээх
            </Button>
          </VStack>

          <Divider />
          <HStack my="20px" justifyContent="space-between" px="80px">
            <Image
              w={"200px"}
              src="https://cdn.discordapp.com/attachments/1000991557886947358/1061272837555507200/Asset_6.png"
            />
            <Text color={"white"}>© 2023 Bit Academy</Text>
            <HStack>
              <Link
                href="https://www.facebook.com/bit.academy.official"
                target="_blank"
              >
                <IconButton
                  bg="none"
                  color={green}
                  aria-label="facebook"
                  icon={<BsFacebook size={"30px"} />}
                />
              </Link>
              <Link
                href="https://www.facebook.com/bit.academy.official"
                target="_blank"
              >
                <IconButton
                  bg="none"
                  color={green}
                  aria-label="facebook"
                  icon={<BsInstagram size={"30px"} />}
                />
              </Link>
              {/* {icon.map((el: any, ind: number) => {
                return (
                  <el/>
                )
              })} */}
            </HStack>
          </HStack>
        </Flex>
      </main>
    </>
  );
}
